sonar.organization=<ключ-організації-в-sonar>
sonar.projectKey=<ключ-проєкту>
sonar.sources=calculator.py,src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true